instances:
- name: instance1
  url: https://gwre-devexp-ci-production-devci.gwre-devops.net
  username: login
  password: password
  scrape_interval: 100
  builds_filters:
  - name: filter1
    filter:
      status: success
      running: false
      canceled: false
      count: 1
- name: instance2
  url: https://gwre-devexp-ci-poc-kdc-devci.gwre-devops.net
  username: login
  password: password
  scrape_interval: 80
  builds_filters:
  - name: filter1
    filter:
      build_type: ca_generation_1
      status: failure
      running: false
      canceled: false
      count: 1
  - name: filter2
    filter:
      build_type: ca_generation_2
      branch: master
      status: success
      running: false
      canceled: false
      count: 1
