instances:
- name: prod
  url: https://gwre-devexp-ci-production-devci.gwre-devops.net
  username: login
  password: password
  scrape_interval: 600
  concurrency_limit: 5
  builds_filters:
  - name: prod-filter1
    filter:
      build_type: BillingCenter_Autobuild
      status: success
      running: false
      canceled: false
  - name: prod-filter2
    filter:
      build_type: BillingCenter_DailyTests
      status: failure
      running: false
      canceled: false
- name: dev
  url: https://gwre-devexp-ci-poc-kdc-devci.gwre-devops.net
  username: login
  password: password
  scrape_interval: 80
  concurrency_limit: 10
